# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\"\x1c\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1e\n\x0cUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32U\n\x0bUserManager\x12\x46\n\x0f\x43heckUserExists\x12\x18.userservice.UserRequest\x1a\x19.userservice.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=35
  _globals['_USERREQUEST']._serialized_end=63
  _globals['_USERRESPONSE']._serialized_start=65
  _globals['_USERRESPONSE']._serialized_end=95
  _globals['_USERMANAGER']._serialized_start=97
  _globals['_USERMANAGER']._serialized_end=182
# @@protoc_insertion_point(module_scope)
